KrishnaKTechnocredits/SeleniumTechnoJun20

- src/aavruti/FieldValidations.java
**1) After Adding Details in Form**
**2) After Resetting Form**
**3) After Navigating to new URL**
**4) Message on Eclipse**
> Aavruti_Assignment_1

- src/abhishek/Assignment1.java
output:
test title passed
All text field are reset
gender radio button is reset
Experience radio button is reset
learn language radio buuton is reset
Dreamcompany radio button is reset
test passed
> Assignment_01_60minutes

- src/vaishnavi_SeleniumBasics/VerifyFirstWebPage.java
> Vaishnavi_Assignment_1_Done

- src/palak/FormAssignment1.java
> Palak_Assignment_1

- src/ajit/Assignment1.java
> Ajit_Assignment_1

- src/barkha/Assignment1.java
> Barkha_Assignment_1

- src/mahesh/FirstTest.java
> Mahesh Selenium Assignment 1 45Mins

- src/prashant/DemoTest.java
Adding folder to project. Plz approve the request.
> Adding folder

- src/aashtha/ValidateForm.java
> Aastha_Assignment_1

- src/nikhil/FormValidations.java
- Completed and pushed Assignment # 1
- Please review and comment.
-PFB screenshots of the various steps of the output of program:-
**1. Opening the form and entering values in the fields:-**
**2. Resetting the entered values:-**
**3. URL redirection:-**
**4. Console o/p messages:-**
> Nikhil_Assignment_1_Done

- src/aditi/FormFieldValidations.java
**Console Output:**
**FormData:**
**Form Reset:**
**Url Navigation**
> ADT_Selenium_Assignment1_Done

- src/viresh/assignment1/HtmlFormOperations.java
@KrishnaKTechnocredits Kindly review and comment
> Viresh_Assignment_1_Done

- src/amita/SeleniumFormVerification.java
Please Review Selenium Assignment_1 ...
> AMITA_Assignment_1_Done

- src/anup/SeleniumFormTest.java
> Anup_Assignment_1_Done

- src/jagdeesh/Assignment1.java
> Commit Code Jagadeesh_Assignment_1

- src/anshu/FindElementAndClickTestCase.java
> Anshu-Assignment-1

- src/archana/SeleniumAss1.java
> Archana_Selenium_Assignment_1

- src/raj/FindElementResetVerify.java
> Raj_Assignment_1_Done

- src/madhura/TechnocreditsForm.java
> Madhura_Assignment_1

- src/rachana/FormValidations.java
> Rachana_Assignment_1_Done

- src/pranita/Assgnmnt_1_FillFormDetails.java
> Pranita_Assignment1_Done_30min

- src/suparna/BackAndForthWebPageTest.java
- src/suparna/ResetButtonAndGoURL.java
> Assignment No 1 and 2

- src/kartikey/WebElements_HtmlPage.java
> Kartikey_Selenium_Assignment_1_40mins

- src/amita/FacebookLoginPageValidation.java
> AMITA_Assignment_2_Done

- src/madhura/FacebookSignInPage.java
> Madhura_Assignment_2

- src/anup/FacebookVerification.java
> Anup_Assignment_2_Done

- src/barkha/FB_Dropdown.java
> Barkha_Assignment_3

- src/anshu/FindElementInFacbookUsingXPath.java
> Anshu-Assignment-3

- src/aavruti/FacebookRegistration.java
> Aavruti_Assignment_3

- src/mahesh/SelectTest.java
> Mahesh_Assignment_3_30Mins

- src/raj/FacebookSignup.java
> Raj_Assignment_3_Done

- src/nikhil/FacebookSignUp.java
- Completed and pushed Assignment # 3.
- Please review and comment.
- PFB screenshots of various steps of the program:-
**1. Facebook page rendering**
**2. Inputting values in the fields**
**3. Console output**
> Nikhil_Assignment_3_Done

- src/vaishnavi_SeleniumBasics/FacebookSignUp.java
> Vaishnavi_Assignment_3_Done

- src/palak/FacebookSignUpValidation.java
> Palak_Assignment_3

- src/aashtha/FacebookSignUp.java
> Aastha_Assignment_3_Done

- src/viresh/assignment3/FBLocatorTechniques.java
@KrishnaKTechnocredits ,please review and comment
> Viresh_Assignment_3_Done

- src/jagdeesh/Assignment3.java
Please review my code.
Output :
> Jagadeesh_Assignment_3_50min

- src/madhura/FacebookSignIn.java
> Madhura_Assignment_3

- src/abhishek/Assignment_03.java
output:
Facebook – log in or sign up
you are on the signup page
> Assignment_03

- src/shruti/FormData.java
- src/shruti/GitNavigation.java
> Shruti assignment 2

- src/anshu/FacebookNavigation.java
> Anshu-Assignment-2

- src/pranita/Assgnmnt_1_FillFormDetails.java
- src/pranita/Assignmnt2_FBLogin.java
> Pranita_assignment_2_Done_25mins

- src/jagdeesh/Assignment2.java
Please review my code.
Output:
> Commit code for Jagadeesh_Assignment_2

- src/ajit/NavigationConcept.java
> Ajit_Assignment_2_Completed

- src/aavruti/FacebookValidations.java
> Aavruti_Assignment_2

- src/viresh/assignment2/PageNavigation.java
@KrishnaKTechnocredits Kindly review and comment.
> Viresh_Assignment_2_Done20Mins

- src/raj/NavigateAndVerify.java
> Raj assignment 2

- src/mahesh/Navigation.java
> Mahesh_Selenium_Assignment_2_45Mins

- src/aashtha/TestBackAndForth.java
> Aastha_Assignment_2_Done

- src/kartikey/FacebookGoogleNavigateAndNavigateBack.java
> Kartikey_Selenium_Assignment_2_20mins

- src/nikhil/FacebookToGoogle.java
- Completed and pushed Assignment # 2.
- Please review and comment.
-PFB screenshots of various steps of the program execution:-
**1. Facebook login done**
**2. Navigated to Google**
**3. Back to Facebook...**
**4. Forward to Google and refresh**
**5. Console o/p messages for testing**
> Nikhil_Assignment_2_Done

- src/abhishek/Assignment2.java
output:
Facebook page opened sucessfully
user is on Facebook page 
You are on Google page
You are on Facebook page
You are on Google page
You are on Google page
> Abhishek_Assignment_02

- src/palak/FacebookAssignment.java
> Palak_Assignment_2

- src/barkha/Facebook.java
> Barkha_Assignment_02

- src/archana/SeleniumAss2.java
> Archana_Selenium_Assignment_2_Done

- src/vaishnavi/Facebook.java
> Vaishnavi_Assignment_2_Done

- src/prashant/Facebook.java
Assignment 2 done. 
Scenarios covered
1. Navigation Commands 
2. Browser commands
> Prashant_Assignment_2

- src/harshad/selenium_assignment1/ValidateHtmlFormElements.java
-> Selenium Assignment 1 Done.
-> Screenshot of output below:
> Harshad_Selenium_Assignment_1_Done

- src/harshad/selenium_assignment2/ValidationOfNavigationCommands.java
-> Selenium Assignment 2 Done
-> Screenshot of output as below:
> Harshad_Selenium_Assignment_2_Done

- src/kartikey/FacebookLoginByXpath.java
> Kartikey_Assignment_3_25min

- src/amita/FacebookSignupPageValidation.java
> AMITA_Assignment_3_Done

- src/anup/FacebookSignup.java
> Anup_Assignment_3_Done

- src/aditi/FaceBookSignUpPage.java
> ADT_Assignment_3_done

- src/pranita/Assignment_3_FBSignUpPage.java
> Pranita_Assignment_3_Done_30mins

- src/rachana/AccessFacebookWebElement.java
> Rachana_Assignment_3_Done

- src/rachana/FacebookNevigationValidation.java
> Rachana_Assignment_2_Done

- src/suparna/LinkOpeartion.java
Test case 1: open web page of MissingLink.html  --> pass
Total no of Link count  on MisingLink.html is :6
Test case 2 : Find total Link  tag count  Pass
link available  in this form are 
1:Google
2:AutomationByKrishna
3:Facebook
4:Instagram
5:Globant
6:Synechron
link tag for which  link adress is missing   are 
missingLink-> Instagram
value of href tag is :
link tage for which  href attribute is missing are 
missingLink-> Synechron
value of href tage is : null
> Suparna-Assignment04

- src/barkha/FindMissingLink.java
> Barkha_Assignment_4

- src/aashtha/MissingLink.java
> Aastha_Assignment_4_Done

- src/jagdeesh/Assignment4.java
Please review my code.
Output:
> Assignment_Jagadeesh_4

- src/palak/FindAndPrintLinks.java
> Palak_Assignment_4

- src/anshu/MissingLink.java
> Anshu-Selenium-Assignment-04

- src/raj/MissingLinksFormAutomate.java
> Raj_Assignment_4_Done

- src/rachana/HyperLinksTesting.java
> Rachana_Assignment_4_Done

- src/mahesh/LinksTest.java
> Mahesh_Selenium_Assignment_4_30Mins

- src/abhishek/Assignment_4.java
output:
user is successfully hit the URL
output: 6 links on the page
List of all Links are 
Google
AutomationByKrishna
Facebook
Instagram
Globant
Synechron
Missing Link -> Instagram
href is missing -> Synechron
> Abhishek assignment 04

- src/vaishnavi_SeleniumBasics/MissingLink.java
> Vaishnavi_Assignment_4_Done

- src/nikhil/FormScenarios.java
-Completed and pushed Assignment # 4.
-PFB screenshots of the execution of the code:-
**1. Page rendered...**
**2. Console output**
> Nikhil_Assignment_4_Done

- src/viresh/assignment4/MissingLinkOperations.java
@Krishna, Please review and comment
> Viresh_Assignment_4_30Mins

- src/madhura/MissingLinkForm.java
> Madhura_Assignment_4

- src/shruti/FindElementsEx.java
> Shruti Assignment 4- 40 minutes

- src/archana/SeleniumAss4.java
> Archana_Assignment_4_Done

- src/pranita/Assignment_4_MissingLinks.java
> Pranita_Assignment_4_Done_30mins

- src/harshad/selenium_assignment3/SelectDropDownDemoWithFacebookSignUp.java
-> Selenium Assignment 3 Done using id or name attribute. Also using xpaths in other method.
-> Screenshot of Output as below:
> Harshad_Selenium_Assignment_3_Done

- src/harshad/selenium_assignment4/LinksValidationsInsideDom.java
-> Selenium Assignment 4 Done.
-> Screenshot of output as below:
Please review & comment.
> Harshad_Selenium_Assignment_4_Done

- src/kartikey/MissingLinks.java
> KartikeySelenium_Assignment_3_25min

- src/amita/MissingLinkValidation.java
please review Assignment-4
Thank you...
> AMITA_Assignment_4

- src/aditi/MissingLinks.java
> ADT_Assignment_4

- src/anup/MissingLinkValidation.java
> Anup_Assignment_4_done

- src/ajit/BrokenLinks.java
> Ajit_Assignment_4

- src/aavruti/MissingLink.java
Missing Link
**After making suggested changes:**
**Old Screenshot:**
> Aavruti_Assignment_4

- src/barkha/ScrollingFunction.java
- src/barkha_base/PredefinedFunctions.java
> Barkha_Assignment_5

- src/vaishnavi_SeleniumBasics/MultiDropdown.java
> Vaishnavi_Assignment_5_Done

- src/anshu/SelectMultiDropDownOption.java
> Anshu-Assignment-5

- src/aavruti/MultiDropDown.java
- src/aavruti/base/PredefinedActions.java
> Aavruti_Assignment_5

- src/jagdeesh/MultiSelectDropdown.java
> Jagadeesh_Assignment_05

- src/raj/AutomateMultiDropdown.java
> Raj_Assignment_5_Done

- src/vaishnavi_CodingExams/ComapnyTitles.java
> Vaishnavi _coding _exam _1_Done

- src/rachana/CoadingExam/Exam1.java
- src/rachana/base/PredefinedActions.java
> Rachana_CodingExam_1_60min

- src/suparna/Test/WebTableOpeartionTest01.java
- src/suparna/basics/base/PredefineAction.java
O/P
Test case 1 : Check Title column value and Navigated page title value  
Expected Title Vaue --> 			 Actual Title Value -->  			 Test Case Result
Home Page | Globant --> We Create Digital Journeys | Globant -->  Test case  fail
ThoughtWorks: A Global Software Consultancy | ThoughtWorks --> ThoughtWorks: A Global Software Consultancy | ThoughtWorks --> Test case  Pass
EPAM | Enterprise Software Development, Design & Consulting --> EPAM | Enterprise Software Development, Design & Consulting --> Test case  Pass
Tata Consultancy Services Technology, Digital Solutions, Consulting --> IT Consulting Services & Business Solutions | Tata Consultancy Services (TCS) -->  Test case  fail
Home | Synechron --> Verify Table -->  Test case  fail
Test case 2:Find Comapany whoes link is missing 
Llink …
> Suparna-codingTest01

- src/suparna/Assignment07/ManagerIDOperation.java
O/P
Manager Id 	 Reporting EMP count 
20209	 	3
10101	 	2
20205	 	4
Manager id to whom max employ reporting is 
4   employees reporting to  --> 20205
> Suparna-Assignment07

- src/suparna/Assignment08/UserNameValidation.java
O/P
FirstName 	 LastName 	 UserName 
Maulik		Kanani		mkanani
Krishna		Kanani		kkanani
Dhara		Boda		dboda
Abhishek		Sharma		asharma
Priya		Patro		ppatro
Test case pass
> Suparna-Assignment08

- src/rachana/UserNameValidation.java
> Rachana_Assignment_8_Done

- src/pranita/Assignment_8_WebTable_UserNameValidation.java
- src/pranita/basic/PredefinedFunctions.java
> Pranita_Assignment_8_Done_20mins

- src/ajit/testScripts/ValidateUserName.java
> Ajit_Assignment_8_Completed

- src/anup/UserNameValidation.java
- src/anup/basics/PredefinedActions.java
> Anup_Assignment_8_done

- src/aditi/EmployeeInfo.java
- src/aditi/EmployeeTableUniqueRow.java
> ADT_Assignment_8_Done

- src/aditi/UserNameValidation.java
- src/aditi/base/PredefinedActions.java
> ADT_Assignment_7_Done

- src/amita/DemoTableUserNameValidation.java
- src/amita/base/PredefinedActions.java
> AMITA_Assignment_8_Done

- src/nikhil/UsernameValidation.java
-Completed and pushed Assignment # 8.
-PFB screenshot of console output:-
> Nikhil_Assignment_8_Done_30Min

- src/archana/SeleniumAss8.java
> Archana_Assignment_8_Done

- src/aashtha/UsernameVerification.java
> Aastha_Assignment_8_Done

- src/barkha/WebTable_UserNameValidation.java
> Barkha_Assignment_8

- src/viresh/assignment7/UserNameValidation.java
@KrishnaKTechnocredits , please review and comment
> Viresh_Assignment_7(8)_Done_20Mins

- src/raj/UserNameValidation.java
> Raj_Assignment_8_Done

- src/mahesh/WebTableUserNameValidation.java
- src/mahesh/base/PredefinedActions.java
> Mahesh_Selenium_Assignment_8_30Mins

- src/vaishnavi_SeleniumBasics/UsernameValidation.java
> Vaishnavi_Assignment_8_Done

- src/aavruti/UsernameVerification.java
> Aavruti_Assignment_8

- src/archana/SeleniumAss4.java
- src/archana/SeleniumAss7.java
> Archana_Assignment_7_done

- src/pranita/Assignment_7_WebTableEmployeeManager.java
- src/pranita/Exam_1.java
> Pranita assignment 7

- src/amita/EmployeeManagerWebTable.java
- src/amita/base/PredefinedActions.java
> AMITA_Assignment_6_Done

- src/anup/WebTableValidations.java
- src/anup/basics/PredefinedActions.java
> Anup_Assignment_7_Done

- src/kartikey/WebTableEmployeeManager.java
> Kartikey_Assignment_6_Done

- src/aashtha/EmpManagerTable.java
> Aastha_Assignment_6_Done

- src/nikhil/EmployeeManager.java
- src/nikhil/base/PreDefinedActions.java
-Completed and pushed Assignment # 6.
-PFB screenshots of the steps of the execution of the code:-
**1. Navigating to the Demo Table tab...**
**2. Console output**
> Nikhil_Assignment_6_Done

- src/vaishnavi_Base/PredefinedAction.java
- src/vaishnavi_SeleniumBasics/Employee.java
> Vaishnavi_Assignment_6_Done

- src/viresh/assignment6/WebTableOps.java
- src/viresh/base/PredefinedActions.java
Hi Krishna, please review and comment.
> Viresh_Assignment_6_Done

- src/barkha/WebTableFuntions.java
- src/barkha_base/PredefinedFunctions.java
> Barkha_Assignment_7

- src/mahesh/ManagerTable.java
- src/mahesh/base/PredefinedActions.java
> Mahesh_Assignment_7_45Mins

- src/madhura/EmployeeManagerTable.java
- src/madhura/MultiDropdown.java
- src/madhura/base/PredefinedActions.java
> Madhura_Assignment_6

- src/anshu/AutomationOnWebTable.java
- src/anshu/base/PredefinedProperty.java
> Anshu-Assignment-6-Done

- src/palak/WebTableEmployeeReporting.java
> Palak_Assignment_7

- src/aavruti/EmpManagerWebTable.java
- src/aavruti/base/PredefinedActions.java
1) Find how many employees reporting to each manager ID. 
2) Find maximum employees reporting to which manager ID.
> Aavruti_Assignment_6

- src/archana/SeleniumExam1.java
> Archana_Selenium_codingExam_1_50mins

- src/vaishnavi_SeleniumBasics/IFrame.java
> Vaishnavi_Assignment_11_done

- src/anup/IFrameValidations.java
> Anup_Assignment_11_Done

- src/abhishek/Iframe.java
output:
user is on Selenium Projects page
Test passed : This is Maulik.
> Abhishek_Assignment11

- src/amita/IframeValidation.java
> AMITA_Assignment_11_Done

- src/aditi/SwitchingIFrames.java
- src/aditi/utility/PropertyFileOperation.java
> Added property file reading code for my reference (PropertyFileOperation.java) --
> ADT_Assignment_10_done

- src/pranita/Assignment_11_IFrame.java
> Pranita_Assignment_11_Done

- src/barkha/FramesHandle.java
> Barkha_Assignment_11

- src/sonal/Assignment11.java
> Assignment11

- src/aavruti/IFrameDemo.java
> Aavruti_Assignment_11

- src/anshu/AutomationOnIFrame.java
> Anshu-Assignment-11-Done

- src/palak/IframeAssignment.java
> Palak_Assignment_11

- src/raj/IFrameValidation.java
> Raj_Assignment_11_Done

- src/mahesh/IFrameTest.java
> Mahesh_Assignment_11_30Mins

- src/pooja/Assignment_8.java
> Pooja assignment 8

- src/ajit/testScripts/iFrameConcept.java
> Ajit_Assignment_11_Completed

- src/aashtha/TestIframes.java
> Aastha_Assignment_11_Done

- src/rachana/IframeDemo.java
- src/rachana/base/PredefinedActions.java
- src/rachana/navigation/HomePageMenuNavigation.java
> Rachana_Assignment_11_Done

- src/archana/SeleniumAss11.java
> Archana_Assignment_11_done

- src/suparna/Assignment10/FeatchDataFromPropertyFile.java
- src/suparna/basics/base/PredefineAction.java
- src/suparna/config/credentials.properties
- src/suparna/utility/PopertyFileRead.java
String display in Alert is correct : Test case pass
> Suparna-Assignment10

- src/jagdeesh/IframeDemo.java
> Jagadeesh_Assignment_11

- src/suparna/Assignment11/IFrameSwitch.java
Expected Result : Selenium Projects
Actual Result : Selenium Projects
Test case Pass :
Expected Result : This is Maulik.
Actual Result :This is Maulik.
Test case Pass :
> Suparna assignment11

- src/viresh/assignment10/IframeOps.java
- src/viresh/utility/SetUp.java
Hi Krishna, please review and comment:
> Viresh_Assignment_10_Done

- src/nikhil/JumpingIFrames.java
-Completed and pushed Assignment # 11.
**NOTE: I have purposefully used implicit wait in this code as due to slow Internet, each web-element was taking a very long time to load. By using implicit wait code becomes simpler.** 
-PFB screenshot of console output:-
> Nikhil_Assignment_11_Done

- src/kartikey/IFrameSwitch.java
> Kartikey_Assignment_11_done

- src/anshu/AlertValidationOnWebElemet.java
- src/anshu/base/BasicElemet.properties
- src/anshu/base/PredefinedProperty.java
> Anshu-Assignment-10-Done

- src/rachana/EmployeeManagerTableTest.java
> Rachana_Assignment_7_Done

- src/anup/ValidateAlertInputFromPropertyFile.java
- src/anup/basics/PredefinedActions.java
- src/anup/config/BasicElementData.properties
> Anup_Assignment_10_Done

- src/kartikey/VerifyUserNme.java
> Kartikey_Assignment_8_done

- src/aditi/ValidateAlertMsgUsingPropertyFile.java
- src/aditi/base/PredefinedActions.java
- src/aditi/config/BasicElementData
> ADT_Assignment_9_Done

- src/amita/ReadInputPropertiesFile.java
- src/amita/base/PredefinedActions.java
- src/amita/config/BasicElementData.properties
> AMITA_Assignment_10_Done

- src/nikhil/AlertFromPropertyFile.java
- src/nikhil/config/BasicElementData.properties
-Completed and pushed Assignment # 10.
-PFB screenshots of steps of the code execution:-
**1. Input text and alert**
**2. Console output**
> Nikhil_Assignment_10_Done

- src/nikhil/assignment_9/Employee.java
- src/nikhil/assignment_9/Operations.java
-Completed and pushed Assignment # 9.
-PFB the screenshot of console output:-
> Nikhil_Assignment_9_Done

- src/archana/Config.properties
- src/archana/SeleniumAss10.java
> Archana_Assignment_10_Done

- src/jagdeesh/AlertMessage.java
- src/jagdeesh/config/AlertMessage.properties
> Jagadeesh_Assignment_10

- src/viresh/assignment9/AlertDemo.java
- src/viresh/assignment9/config/BasicElementsData.properties
- src/viresh/base/PredefinedActions.java
@KrishnaKTechnocredits Please review and comment
> Viresh_Assignment_9_Done40Mins

- src/abhishek/AlertHandleWithProptiesFile.java
- src/abhishek/config/BasicElementData.properties
output:
Alert Message is Correct : Abhishek and Singh and abhiXyZ
> Abhishek_Assignment_10

- src/viresh/assignment8/EmpManager.java
- src/viresh/assignment8/FindDuplicateRow.java
@KrishnaKTechnocredits please review and comment
> Viresh_Assignment_8_Done

- src/rachana/PropertyFileDemo.java
- src/rachana/config/BasicElements.properties
> Rachana_Assignment_10_Done

- src/barkha/ReadPropertyFile_HandleAlert.java
- src/barkha_config/BasicElements.properties
> Barkha_Assignment_10

- src/mahesh/BasicElementValidation.java
- src/mahesh/config/BasicElementData.properties
> Mahesh_Assignment_10_35Mins

- src/pranita/Assignment_10_validateAlert.java
- src/pranita/config/BasicElementsData.properties
> Pranita_Assignment_10_Done

- src/raj/EmployeeManagerTable.java
- src/raj/UniqueRowValidation.java
> Raj_Assignment_9_Done

- src/sonal/Assignment10.java
- src/sonal/Config/Property.properties
> Assignment10

- src/aashtha/AlertMessageVerification.java
- src/aashtha/base/AlertMessageVerificationData
> Aastha_Assignment_10_Done

- src/barkha/EmployeeRowsValidation.java
- src/barkha/EmployeeRowsValidation_Employee.java
> Barkha_Assignment_9

- src/abhishek/UsernameVerification.java
output-
employee Maulik Kanani is present:  Test passed
employee Krishna Kanani is present:  Test passed
employee Dhara Boda is present:  Test passed
employee Abhishek Sharma is present:  Test passed
employee Priya Patro is present:  Test passed
> Abhishek_Assignment_08

- src/jagdeesh/Employee.java
- src/jagdeesh/UniqueEmpDetails.java
- src/jagdeesh/UserNameValidation.java
> Jagadeesh_Assignment_08

- src/raj/ValidatePropertyFile.java
- src/raj/selenium/config/BasicElementData.properties
> Raj_Assignment_10_Done

- src/suparna/Assignment09/EmpDetails.java
- src/suparna/Assignment09/EmpObjComp.java
- src/suparna/basics/base/PredefineAction.java
O/P
Total no of duplicate  Emp record count is 1
Below are duplicate records
76585 Sumit Mate 20205 7002-Finance
Total no of EMP records are : 9
> Suparna-Assignment09

- src/kartikey/VerifyAlertUsingPropertyFile.java
- src/kartikey/config/BasicElementsData.properties
> Kartikey_Assignment_10_done

- src/abhishek/EmployeeManagerTable.java
Output:
Number of employees reporting to each manager ID : 
20209 : 3
10101 : 2
20205 : 4
Maximum employee reporting to ManagerId : 
20205 : 4
> Abhishek_Assignment_07

- src/palak/AlertHandle.java
- src/palak/config/BasicElementData.properties
> Palak_Assignment_10

- src/pranita/Asgnmnt9_EmployeeManagerTable.java
- src/pranita/Asgnmnt9_UniqueRowValidation.java
> Pranita_Assignment_9_Done

- src/aavruti/AlertMessageValidation.java
- src/aavruti/base/PredefinedActions.java
- src/aavruti/config/BasicElementsData.properties
> Aavruti_Assignment_10

- src/ajit/testScripts/EmpMngrUniqueRowsValidation.java
- src/ajit/testScripts/EmployeeManagerDetails.java
> Ajit_Assignment_9_Completed

- src/ajit/Config/BasicElementsData.properties
- src/ajit/testScripts/ReadDataFromPropertyFile.java
> Ajit_Assignment_10_Completed

- src/vaishnavi/PropertyFileOperations/PropertyFileOperation.java
- src/vaishnavi/confiig/BasicElementsData.properties
- src/vaishnavi_SeleniumBasics/ValidationUsingPropertyFile.java
> Vaishnavi_Assignment_10_Done

- src/sonal/Assignment9.java
- src/sonal/Employee.java
> Assignment 9

- src/ajit/base/PredefinedActions.java
- src/ajit/testScripts/EmployeeReportingToManager.java
> Ajit_Assignment_7_Done

- src/rachana/TestEmployeeTable.java
- src/rachana/assignment9/Employee.java
> Rachana_Assignment_9_Done

- src/sonal/Assignment7.java
> Assignment 7

- src/palak/WebTableVerifyUsername.java
> Palak_Assignment_8

- src/aavruti/hashcodeAndequals/EmpManagerDetails.java
- src/aavruti/hashcodeAndequals/EmpManagerTableUniqueData.java
> Aavruti_Assignment_9

- src/palak/WebTableEmployeeManager.java
- src/palak/WebTableFindDuplicateRow.java
> Palak_Assignment_9

- src/mahesh/EmployeeManagerData.java
- src/mahesh/WebTableUniqueRows.java
- src/mahesh/base/PredefinedActions.java
> Mahesh_Assignment_9_35Mins

- src/aashtha/aastha_assignment_9/Employee.java
- src/aashtha/aastha_assignment_9/EmployeeRecordVerification.java
> Aastha_Assignment_9_Done

- src/vaishnavi_SeleniumBasics/EmployeeDetails.java
- src/vaishnavi_SeleniumBasics/EmployeeUsingEqualsHashCode.java
> Vaishnavi_Assignment_9_Done

- src/amita/EmployeeManagerTableData.java
- src/amita/WebTableUniqueRowValidation.java
> AMITA_Assignment_9_Done

- src/anshu/EmployeeDetails.java
- src/anshu/EqualityComparisonInWebTable.java
> Anshu-Assignment-9

- src/anshu/ValidateUsernameInWebTable.java
> Anshu-Assignment-8

- src/anup/EmployeeManager.java
- src/anup/EmployeeManagerUniqueRowsValidation.java
- src/anup/basics/PredefinedActions.java
> Anup_Assignment_9_Done

- src/aavruti/ActionsDemo.java
> Aavruti_Assignment_12

- src/palak/ActionClassAssignment.java
> Palak_Assignment_12

- src/vaishnavi_SeleniumBasics/DoubleClick.java
- src/vaishnavi_SeleniumBasics/DragAndDrop.java
- src/vaishnavi_SeleniumBasics/MouseHover.java
> Vaishnavi_Assignment_12_Done

- src/barkha/DoubleClick.java
- src/barkha/DragAndDrop.java
- src/barkha/MouseHover.java
> Barkha assignmet 12

- src/sonal/Assignment12.java
> Assignment12

- src/aditi/ActionDoubleClick.java
- src/aditi/ActionDragAndDrop.java
- src/aditi/ActionMouseHover.java
- src/aditi/base/PredefinedActions.java
> ADT_Assignment_11_Done

- src/amita/DoubleClickAction.java
- src/amita/DragAndDropAction.java
- src/amita/MouseHoverAction.java
> AMITA_Assignment_12_Done

- src/aashtha/TestActionClass.java
> Aastha_Assignment_12_Done

- src/ajit/testScripts/ActionClassConcepts.java
> Ajit_Assignment_12_Done

- src/abhishek/EmployeeManagerTable.java
- src/abhishek/UniqueRowValidation.java
output:
Duplicate row -> Employee Id : 76585 and Employee Name : Sumit Mate
Total no of unique rows---> 8
> Abhishek_assignment_09

- src/anshu/DoubleClickValidation.java
- src/anshu/DragNDropValidation.java
- src/anshu/MouseHoverValidation.java
> Anshu-Assignment-12

- src/raj/ActionDoubleClick.java
- src/raj/ActionDragAndDrop.java
- src/raj/ActionMouseHover.java
> Raj_Assignment_12_Done

- src/aavruti/BrowserHandling.java
> Aavruti_Assignment_13

- src/barkha/HandleMultiBrowsers.java
> Barkha_Assignment_13

- src/palak/MultiTabHandle.java
> Palak_Assignment_13

- src/vaishnavi_SeleniumBasics/MultiBrowserTab.java
> Vaishnavi_Assignment_13_Done

- src/mahesh/ActionTest.java
> Mahesh_Assignment_12

- src/viresh/assignment11/ActionsExercise.java
@harshvegada Please review and comment, Thank you.
> Viresh_Assignment_11_Done

- src/madhura/MultipleWindows.java
> Madhura_Assignment_13

- src/aashtha/TestMultiTabBrowsersHandle.java
> Aastha_Assignment_13_Done

- src/viresh/assignment13/MultBrowserHandle.java
- src/viresh/assignment13/New Tab Open.html
- src/viresh/utility/SetUp.java
@harshvegada , Please review and comment
> Viresh_Assignment_13_Done

- src/nikhil/MultiTabHandling.java
-Completed and pushed Assignment # 13.
-PLease review and comment.
-PFB the screenshot of console output:-
:-
> Nikhil_Assignment_13_Done

- src/anup/ActionClassUses.java
> Anup_Assignment_12_Done

- src/aditi/MultiBrowserHandling.java
> ADT_Assignment_12_Done

- src/anup/MultiTabValidation.java
> Anup_Assignment_13_Done

- src/amita/MultiTabWindowHandling.java
> AMITA_Assignment_13_Done

- src/aavruti/CodingExam2.java
> Aavruti_Coding_Exam_2_1Hr

- src/aditi/Exam2.java
> ADT_Selenium_Exam2_1hr20Mins

- src/barkha/SeleniumTest2.java
- src/barkha/TestNG_Practice.java
- src/barkha/testng.xml
- src/barkha_utility/PropertyFileOperation.java
> Barkha_SeleniumTest_2

- src/vaishnavi_CodingExams/SnapDealValidation.java
> Vaishnavi_Coding_Exam_2_Done

- src/ajit/CodingExam2.java
> Ajit_CodingExam_2_Completed

- src/anshu/MultiWindowAndIframeCodeExam.java
> Anshu-ExamCode-2-Done

- src/aashtha/SnapdealLogin.java
> Aastha_Coding_Exam_2_2hrs

- src/madhura/CodingExam_2.java
> Madhura_Coding_Exam_2

- src/mahesh/Exam/CodingExam2.java
- src/mahesh/Exam/CodingExam_2.java
> Mahesh selenium coding exam 2

- src/palak/runner/testng.xml
- src/palak/testng/SnapDealExam2.java
Hi @KrishnaKTechnocredits 
Somehow able to get signUp window by using another credentials 
but it is asking Security code everytime so have to enter manually that code 1st then getting sign up window 
Hence, last test case is failing but i have written code for all steps.
> Palak_Coding_Exam_2_1hr30Min

- src/anup/TestNGDemo/SnapDealValidation.java
> Anup_Coding_Exam_2_120mins

- src/viresh/codingExam2/SnapdealSignUp.java
@KrishnaKTechnocredits please review and comment, was not able to validate Steps 8 to 11, due to direct login issue.
> Viresh_Coding_Exam_2_Done

- src/nikhil/SnapdealRegistration.java
-Completed and pushed Coding Exam 2
-Please review and grade.
-PFB screenshot of console output:-
> Nikhil_Coding_Exam_2_Done

- src/amita/SnapDealSignUp.java
Please Review Exam-2 ..
Thank you...
> AMITA_Exam_2

- src/abhishek/CodingExam2.java
- src/abhishek/runner/testng.xml
> Abhishek_codingExam2_Done

- src/anshu/AutomationOnMultiTab.java
> Anshu-Assignment-13-done

- src/jagdeesh/Test2_SnapDeal.java
> Jagadeesh_SeleniumExam_2

- src/archana/CodingExam2.java
> Archana_Selenium_coding_Exam_2

- src/anshu/SnapdealValidation.java
- src/anshu/runner/testng.xml
> Anshu-ExamCode-3(3hr)

- src/mahesh/MultiWindowTest.java
> Mahesh_Assignment_13_30Mins

- src/pranita/Assignment12_ActionClass.java
> Pranita_Assignment_12_Done

- src/pranita/Assignment13_MultiTabHandling.java
> Pranita_Assignment_13_updated

- src/madhura/Coding_Exam_3.java
> Madhura_Coding_Exam_3_3.5hrs

- src/pranita/Assignment_14_DataProvider_Login.java
- src/pranita/runner/14_testng.xml
> Pranita_Assignment_14_Done

- src/palak/SnapDealExam2.java
- src/palak/testng/SnapDealExam3.java
- src/palak/testng/SnapDealNewOrExistUserExam3.java
**2 & 3 scenario Screen shot**
**4 & 5 Scenario screenshot** 
Kindly Ignore Exam2 Code By mistake it got added :(
> Palak coding exam 3_2.5hr

- src/barkha/SeleniumTest3_TestCase1.java
- src/barkha/SeleniumTest3_TestCase2.java
- src/barkha_runner/testng.xml
> Barkha_SeleniumTest_3(2 test cases automate)

- src/nikhil/testNG/DataDrivenLoginTest.java
-Completed and pushed Assignment # 14.
-PFB screenshot of the console output of TestNG run:-
> Nikhil_Assignment_14_Done

- src/mahesh/Exam/CodingExam3/CommonValidations.java
- src/mahesh/Exam/CodingExam3/ValidateOrdersAndCart.java
- src/mahesh/Exam/CodingExam3/ValidateSnapdealEmailLogin.java
- src/mahesh/Exam/CodingExam3/ValidateSnapdealMobileLogin.java
- src/mahesh/runner/testng.xml
> Mahesh_Coding_Exam_3_2hrs 15Mins

- src/mahesh/DataProviderTest.java
> Mahesh_Assignment_14_20mins

- src/aashtha/SnapDealCodingExam3.java
- src/aashtha/runner/testng.xml
> Aastha_Coding_Exam_3_3hrs

- src/aditi/LoginUsingDataProvider.java
> ADT_Assignment_13_Done

- src/kartikey/SnapdealTest234and5.java
- src/kartikey/base/PredDefindActions.java
> Kartikey_Coding_Exam3_234Done_3hrs

- src/raj/LoginUsingDataProvider.java
> Raj_Assignment_13_Done

- src/vaishnavi/runner/testng.xml
- src/vaishnavi_CodingExams/SnapDeal.java
> Vaishnavi_Coding_Exam_3_Done

- src/viresh/codingExam3/Exam3.java
> Viresh_Coding_Exam_3_Done

- src/anshu/LoginValidationByDataProvider.java
> Anshu-Assignment-14-Done

- src/barkha/DataProvider_Login.java
> Barkha_Assignment_14

- src/vaishnavi/TestNgDemo/AutomationByKrishna.java
> Vaishnavi_Assignment_14_Done

- src/palak/testng/LoginUsingDataProvider.java
> Palak_Assignment_14

- src/aavruti/DataDrivenLogin.java
- src/aavruti/base/PredefinedActions.java
- src/aavruti/config/RegistrationLocator.properties
- src/aavruti/runner/loginTestNG.xml
- src/aavruti/utility/PropertyFileOperation.java
> Aavruti_Assignment_14

- src/sonal/Assignment14.java
> Assignmnet14

- src/abhishek/Assignment_13_multitab.java
> Abhishek_Assignment_13_multitab

- src/abhishek/Assignment_14.java
- src/abhishek/base/PredefinedActions.java
> Abhishek_Assignment_14

- src/madhura/UsernameVerification.java
> Madhura_Assignment_8

- src/amita/testNGDemo/SnapDealValidation.java
> AMITA_Coding_Exam_3_Done

- src/anup/TestNGDemo/SnapDealAExam3.java
> Anup_Exam_3_done

- src/rachana/ActionClassDemo.java
> Rachana_Assignment_12_Done

- src/amita/LoginValidationDataProvider.java
> AMITA_Assignment_14_Done

- src/rachana/MultiTabWindowHandleDemo.java
> Rachana_Assignment_13_Done

- src/ajit/testScripts/MultipleBrowserHandling.java
> Ajit_Assignment_13_Completed

- src/ajit/runner/LoginUsingDataProvider.xml
- src/ajit/testScripts/LoginWithDataProviderAnnotation.java
> Ajit_Assignment_14_Completed

- src/madhura/RegistrationWithDataProvider.java
> Madhura_Assignment_14

- src/aavruti/LoginValidationUsingExcel.java
- src/aavruti/base/PredefinedActions.java
- src/aavruti/config/RegistrationLocator.properties
- src/aavruti/runner/loginValidation.xml
- src/aavruti/utility/PropertyFileOperation.java
> Aavruti_Assignment_15

- src/mahesh/ExcelDataProviderTest.java
> Mahesh_Assignment_15_Done_30Mins

- src/kartikey/DoubleClick.java
- src/kartikey/DragAndDrop.java
- src/kartikey/MouseHoverDemo.java
> Kartikey_Assignment_12Done

- src/vaishnavi/PropertyFileOperations/ExcelRead.java
> Vaishnavi_Assignment15_Done

- src/barkha/DataProviderLogin_ReadExcelFile.java
> Barkha_Assignment_15

- src/viresh/assignment14/DataProviderDemo.java
@KrishnaKTechnocredits , please review and comment
> Viresh_Assignment_14_Done

- src/madhura/RegistrationWithXLSheet.java
> Madhura_Assignment_15

- src/anshu/LoginExcelDataProvider.java
> Anshu-Assignment-15-15min

- src/palak/testng/LoginAssignment15.java
> Palak_Assignment_15

- src/ajit/testScripts/DataProviderWithExcel.java
> Ajit_Assignment_15

- src/viresh/assignment15/DataProviderExcel.java
@krishna please review and comment.
> Viresh_Assignment_15_Done

- src/pranita/Assignment_15_ReadDataFromExcel.java
> Pranita_Assignment_15_1_Done

- src/aditi/excelOps/LoginViaExcelData.java
> ADT_Assignment_14

- src/kartikey/LoginUsingExcelReading.java
> Kartikey_Selenium_Assignment_15_Done

- src/nikhil/ExcelDataDrivenLoginTest.java
-Completed and pushed Assignment # 15.
-PFB screenshot of emailable report for the execution of TestNG:-
> Nikhil_Assignment_15_Done

- src/aashtha/LoginUsingDataFromExcel.java
> Aastha_Assignment_15_Done

- .classpath
- src/rachana/DataProviderUsingExcel.java
> Rachana_Assignment_15_Done

- src/amita/LoginUsingExcelData.java
> AMITA_Assignment_15_Done

- src/anup/Datadrivenapproach.java
> Anup_Assignment_14

- src/vaishnavi_SeleniumBasics/UniqueTable.java
> Vaishnavi_Assignment_16_Done

- src/barkha/WebTable_XpathAxes.java
> Barkha_Assignment_16

- src/viresh/assignment16/TableTraverse.java
- src/viresh/assignment16/testng.xml
@KrishnaKTechnocredits  Please review and comment.
> Viresh_Assignment_16_Done

- src/rachana/Assignment16/DataFindingOnDataTable.java
> Rachana_Assignment_16_Done

- src/anshu/AutomationOnDataTable.java
> Anshu-Assignment-16-Done

- src/aashtha/FindUniqueOfficeLocationsPostions.java
> Aastha_Assignment_16_Done

- src/anup/Loginusingexcel.java
> Anup assignment 15

- src/pranita/Assignment_16_UniqueOfficeLocationPosition.java
> Pranita_Assignment_16_Done

- src/palak/testng/FindUniqueLocationAndPosition.java
> Palak_Assingment_16

- src/mahesh/UniqueValuesFromDataTable.java
> Mahesh_Assignment_16_Done

- src/madhura/DataTableLocationPosition.java
> Madhura_Assignment_16

- src/raj/UniqueValuesFromTable.java
> Raj_Assignment_16_Done

- src/amita/FindUniqueOffcLocation.java
Please review  Assignment_16...
> AMITA_Assignment_16_Done

- src/anup/UniqueOfficeLocation.java
> Anup_Assignment_16_Done

- src/anshu/AutomationOnDataTable2.java
> Anshu-Assignment-17-Done

- src/barkha/Webtable_Validation.java
> Barkha_Assignment_17

- src/mahesh/EmployeeMappingWebTable.java
> Mahesh_Assignment_17_Done

- src/viresh/assignment17/EmpMappings.java
@KrishnaKTechnocredits , please review and comment
> Viresh_Assignment_17_Done

- src/pranita/Assignment_17_EmployeesMappingWithOfficeAndPosition.java
> Pranita_Assignment_17_Done

- src/aashtha/FindNoOfEmpOfficePosition.java
> Aastha_Assignment_17_Done

- src/vaishnavi_SeleniumBasics/OfficeMapping.java
> Vaishnavi_Assignment_17_Done

- src/rachana/Assignment17/EmployeeMapping.java
- src/rachana/Assignment17/testngAssignment17.xml
> Rachana_Assignment_17_Done

- src/raj/PositionLocationMapping.java
> Raj_Assignment_17_Done

- src/amita/FindEmployeeOffcAndPosition.java
Please review  Assignment_17...
> AMITA_Assignment_17_Done

- src/anup/OfficePositionEmployeesMapping.java
> Anup_Assignment_17_Done

- src/madhura/DataTablesMapping.java
> Madhura_Assignment_17

- src/sonal/Assignment16.java
> Assignment16

- src/jagdeesh/UniqueOfficeLocation.java
> Jagadeesh_Assignment_16

- src/sonal/Assignment17.java
> assignment17

- src/palak/testng/EmployeeMapping.java
> Palak_Assignment_17

- src/jagdeesh/EmpPerLocAndPosition.java
- src/jagdeesh/UniqueOfficeLocation.java
> Jagadeesh assignment 17

- src/harshad/selenium_assignment16/DataTableEmployeeManagement1.java
->Selenium Assignment 16 Done.
-> Screenshot of Output is below:-
> Harshad_Selenium_Assignment_16_Done

- src/harshad/selenium_assignment17/DataTableEmployeeManagement2.java
-> Selenium Assignment 17 Done.
->Screenshot of Output is below:
Number of Employees count is returning different for some office locations and positions while mapping.
> Harshad_Selenium_Assignment_17_Done

- src/harshad/selenium_assignment15/LoginWithDataProviderDemoUsingExcel.java
->Selenium Assignment 15 Done.
->Screenshot of output as below:-
> Harshad_Selenium_Assignment_15_Done

- src/abhishek/Assignment16_uniqueElementInTable.java
> Abhishek_Assignment16_Done

- src/aditi/UniqueOfcLocationAndPosition.java
- src/aditi/runner/testng.xml
> ADT_Assignment_15_Done

- src/abhishek/Assignment_17.java
> Abhishek_Assignment_17

- src/aditi/EmployeeMapping.java
> ADT_Assignment_16_Done

- src/ajit/runner/ValidateUniqueOfficeLocationAndPosition.xml
- src/ajit/testScripts/ValidateUniqueOfficeLocationAndPosition.java
> Ajit_Assignment_16_Done

- src/vaishnavi_SeleniumBasics/GoIbibo.java
> Vaishnavi_Assignment_18_Done

- src/sonal/Assignment18.java
> Assignment18

- src/palak/testng/Goibibo_Autocomplete_Calendar.java
For return date unable to implement as you explained. 
Some point which i missed :(
> Palak_Assignment_18
